### ISSUE TITLE
Settings saving

### ISSUE THREAD

**Issue by pedrib** [alexhude/FRIEND#13]
It seems that FRIEND doesn't save the plugin settings properly, at least not for me on Linux.

I open a database, set the FRIEND XML, select all the hints, etc, and all is working fine.
If I close the database, and re-open it, I have to do everything again.

FRIEND should save its settings at least on a per database level.

**Comment by alexhude** [comment]
Fixed in a3d021ae19448d87405372eb7758082bcb34e2f6

**Comment by pedrib** [comment]
Awesome, thanks!
