### ISSUE TITLE
Code infringes the copyright of SektionEins GmbH/Stefan Esser

### ISSUE THREAD

**Issue by stefanesser** [alexhude/FRIEND#2]
The code of FRIEND is based on code directly taken from the two IDA extensions WWCD and aarch64_cryptoextension, which you can both find on GitHub.

https://github.com/sektioneins/aarch64_cryptoextension
https://github.com/sektioneins/wwcd

Both of these IDA extensions are NOT released under a license that would allow taking their code and putting them into your own project. Especially not if you ask for donations for that code.
Please remove all code you have taken from these two extensions within 30 days or we will take legal actions.

**Comment by alexhude** [comment]
Thank you for your attention to this matter.
Code was updated and all references to the code mentioned above were removed.
Please confirm that your issue is now resolved.
