### ISSUE TITLE
patch capstone failed

### ISSUE THREAD

**Issue by idhyt** [alexhude/FRIEND#20]
I build it for ida7.0

but patch capstone failed, i found capstone has update for patch code, so i checkout last commit available, and build success!

I don't know how to improve this issue, 

this is my change.

https://github.com/idhyt/capstone/commit/3ec472b1420847c5495a7a757a7589b3640684ae

**Comment by in7egral** [comment]
I can't understand what are you doing, really...

```
cd third_party/capstone/src/capstone
mv arch/AArch64/AArch64Module.c arch/AArch64/AArch64Module_bak.c
mv arch/AArch64/AArch64InstPrinter.c arch/AArch64/AArch64InstPrinter_bak.c
git checkout arch/AArch64/AArch64InstPrinter.c arch/AArch64/AArch64Module.c
git pull
cd ../../../../
cmake .
make
```

That's all! Nothing to do anymore.

If you will try to run this:
git diff arch/AArch64/AArch64Module.c arch/AArch64/AArch64Module_bak.c
git diff arch/AArch64/AArch64InstPrinter.c arch/AArch64/AArch64InstPrinter_bak.c

you will get that those files are same.
