### ISSUE TITLE
AArch64_armv8arm_k.xml infringes ARM copyright

### ISSUE THREAD

**Issue by stefanesser** [alexhude/FRIEND#3]
Hey,

just for the record. The AArch64_armv8arm_k.xml file you distribute in this repository are around 460 kb of text that you or someone else have extracted from PDF files by ARM.

You cannot just redistribute 460 kb of text of someone else.

Short extracts would be okay in most countries (e.g. fair use in US) but 460 kb is a huge pile of extracted stuff.

I am not the copyright holder over this, so you can ignore me in this case (and wait maybe for ARM lawyers to tell you the same). I am just showing up a pattern here.
There is a reason why you are the first to distribute a plugin like this: and the reason is you cannot legally distribute 460kb of someone else's copyrighted content.

**Comment by gripedthumbtacks** [comment]
Maybe user does not live in the usa. Copyright laws do not apply globally.

**Comment by jithatsonei** [comment]
hello sir i notice you have an angry german with you, and i believe i have found the solution to prevent him from stomping around on repo ever again!

simply just use this:
```
This software is licensed under the "Anyone But Stefan Esser"
(ABSE) license, descrived below. No other licenses may apply.


------------------------------------------
The "Anyone But Stefan Esser" license
------------------------------------------

Do anything you want with this program, with the exceptions listed
below under "EXCEPTIONS".

In the unlikely event that you happen to make a zillion bucks off of
this, then good for you; consider buying a homeless person a meal.

EXCEPTIONS
----------

Stefan Esser (@i0n1c, that one angry german guy, etc.) may not make use of or
redistribute this program or any of its derivatives.
```
and itll prevent him from ever shitting up your repo ever again

**Comment by alexhude** [comment]
All the information is taken into consideration. Thank you.
