### ISSUE TITLE
Refork required

### ISSUE THREAD

**Issue by alexhude** [alexhude/FRIEND#4]
Recently I asked GitHub support to move this repo to a separate network. This was the only way to detach refs from your forks and cleanup all leftovers. You might have noticed that base repo changed to **TechLord-Forever**.

I am asking for apology from the following people affected by this change:
@BigFoxses @burningcodes @c4rpi @chubbymaggie @crackeer @d4nnyk @flycrane @fredyfx @gh0std4ncer @idkwim @itestings @johnjohnsp1 @killbug2004 @mrexodia @JackBro @mwoolweaver @rweichler @slox3r @small-evil-beast @TechLord-Forever @ThomasKing2014 @threatinteltest @Tourountzis @tUn4 @vaioco @wflk

Sorry for inconvenience. If you are still willing to be linked to this repo for updates, please **remove old repo and refork**.

P.S. Please note that is was not me raising DMCA issue against your repo.

**Comment by mwoolweaver** [comment]
how exactly do I go about removing the old fork? 

Because all I get is a DCMA notice when I try to go to anything to do with it...

![screen shot 2016-12-15 at 8 55 03 am](https://cloud.githubusercontent.com/assets/5729320/21228676/571d4e5c-c2a4-11e6-8bca-9667a6314685.png)

**Comment by alexhude** [comment]
Usually in repo settings in Option section there is a large red button "Delete this repository". But looking at this screenshot I cant see repo settings. Odd. 
You can ask github support to help you (they are very friendly) or refork like others as FRIEND-1.

**Comment by mwoolweaver** [comment]
very strange indeed. As you can see from the URL in the screenshot i am attempting access the settings of the repo. :/

**Comment by mrexodia** [comment]
You had 24 hours to respond to the DMCA request, afterwards github said
they would block your repository. What else did you expect to happen if you
didn't take action within 24 hours?
