### ISSUE TITLE
Only OSX?

### ISSUE THREAD

**Issue by ghost** [alexhude/FRIEND#5]

**Comment by alexhude** [comment]
Yes, unfortunately. Simply because I don't have IDA for windows. But I am pretty sure it is not hard to port it to other platforms. Someone just has to do that :)

**Comment by alexhude** [comment]
Fixed in 5470f2b1d1e334eb9557e7ef665cebea47968aed

**Comment by ghost** [comment]
share build for windows pls

**Comment by kamino** [comment]
@francescogomez look at ``bin/`` there should be binaries your are looking for there

**Comment by ghost** [comment]
![](http://savepic.ru/13002483.gif)

Hmm... it is okay? @kamino

**Comment by alexhude** [comment]
Yep, it is OK, you are using ARM AArch64 hints on x86 assembly :)

**Comment by ghost** [comment]
@alexhude need .xml file for x86?

**Comment by ghost** [comment]
and xml path don't save after restart ida :c

**Comment by ghost** [comment]
for arm worked
![](http://image.prntscr.com/image/8020455bc62244a3be523ea36c3a487f.png)

**Comment by ghost** [comment]
https://gist.github.com/francescogomez/c743d527900c28362ed96aaa55a5104c it is lite x86 assembly xml config
